name: Side effect changed files
description: GitHub Actions to trigger side effect based on changed files
author: KeisukeYamashita

branding:
  icon: radio
  color: gray-dark

inputs:
  bypass:
    description: Bypass the check and outputs for the matching files.
    required: false

  dir_names:
    description: Output unique changed directories instead of filenames.
    required: true
    default: "false"

  dir_names_max_depth:
    description: Limit the directory output to a maximum depth.
    required: false

  escape_json:
    description: Escape JSON special characters.
    required: false
    default: "false"

  files:
    description: Files to check for the side effects.
    required: true

  filters:
    description: Filter the results with glob pattern.
    required: false

  include:
    description: Include the result glob pattern to match the inputs.
    required: false

  json:
    description: Output files in JSON format.
    required: false
    default: "false"

  mapping:
    description: Mapping of the files and its side effects. If you specify `mapping_file` field, it will be merged with the mapping.
    required: false

  mapping_file:
    description: Mapping file of the files and its side effects. If you specify `mapping` field, it will be merged with the mapping.
    required: true
    default: ".github/side-effect.yml"

  matrix:
    description: Output files in a format that can be used for GitHub Action's matrix strategy.
    required: false
    default: "false"

  merge:
    description: Merge the files and its side effects.
    required: false
    default: "false"

outputs:
  changed:
    description: Boolean value indicating whether the files have changed.

  files:
    description: List of changed files.

  files_count:
    description: Number of the files.

runs:
  using: node20
  main: dist/index.js
