name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  action:
    name: GitHub Actions
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.test-action.outputs.files }}

    steps:
      - uses: actions/checkout@v4

      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: "**/*"

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          mapping: |
            .github/workflows/*.yml:
              - src/**/*.ts

            src/*.ts:
              - .github/workflows/*.yml
          matrix: true
          merge: true
    
  hello:
    name: Hello
    runs-on: ubuntu-latest
    needs:
      - action
    strategy:
      matrix:
        path: ${{ fromJson(needs.action.outputs.files) }}

    steps:
      - name: Test
        run: echo "Hello, World from ${{ matrix.path }}"

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test
