name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      contents: write # Needed to create release notes
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
